[common]
eth_jsonrpc_addr = "http://localhost:8545"

[evmtx]
gas_limit = 200000
gas_price = 0
sending_amt = 0 # in wei
chain_id = 2200
duration = "10m"
tpu = 1000 # transaction per time unit
time_unit = "1s"
acc_num = 10000
scenario = "eth_transfer_to_known"

[offchain_feeding]
acc_num = 10
bech_prefix="evmos"
genesis_loc="/Users/mingwang/.tmp-evmosd/config/genesis.json"
denom = "aevmos"
